# Data source paths
data:
  batch_folder: batches/donesection_motion_shotcomp_20250211_231503  # Path to the batch folder
  videos_dir: ../../../datasets/SelectedVideos_video_segments
  label_dir: label_dirs  # Directory where categorized video folders will be saved

# Visualization settings
visualization:
  lazy_load_videos: true  # Flag to control lazy loading

# Server settings
server:
  host: localhost
  port: 8085